### PR TITLE
Carousel workings

### PR DESCRIPTION
**Pull request by amywieliczka**
Joel, I did wind up having to comment out your carousel initialization code in main.js. Is it possible for you to include search.js on your static pages so that the carousel continues working in the static pages?

### CODE REVIEW

**Comment by amywieliczka** [comment]
This is passing in wercker for me, but I can't retry running the build for this pull request since it is Joel's repository. Joel, can you retry the build?

**Comment by JoelCDL** [comment]
I just merged your pull request. Everything now working OK?

**Comment by JoelCDL** [comment]
No problem, I’ll try including search.js

**Comment by JoelCDL** [comment]
Search.js is now loading in my local env, but carousel not working.

**Pull request merged**
